name: Build DockerfileCopsim

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build DockerfileCopsim
      run: docker build . --file DockerfileCopsim --tag unifyai/ivy:copsim$(date +%s)
