name: test-numpy-style-docstrings
on: [push, pull_request]
jobs:
  run-docstring-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install pydocstyle
      - name: Analyse docstrings with pydocstyle
        run: |
          pydocstyle --add-ignore=D100,D101,D102,D103,D104,D105,D205,D400,D401 --convention=numpy $(git ls-files '*.py')
